version: '3'

networks:
    webapp:
services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "8001:80"
        links:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php
            - database
        networks:
            - webapp
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html
        ports:
            - "9002:9000"
        networks:
            - webapp

    database:
        image: mariadb
        container_name: ${APP_NAME}_mariadb
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - mariadbdata:/var/lib/mysql
            - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: 123456
        networks:
            - webapp
# Volumes
volumes:
    mariadbdata:
        driver: local
